import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

_SEVERITY_EMOJI = {"WARNING": "⚠️", "INFO": "ℹ️", "ERROR": "🔴"}


def _build_subject(data: dict) -> str:
    app_name = data.get("app_name", data.get("app_id", "unknown"))
    count = data.get("finding_count", 0)
    if count == 0:
        return f"ignis: no issues found — {app_name}"
    return f"ignis: {count} issue(s) found — {app_name}"


def _build_body(data: dict) -> tuple[str, str]:
    """Return (plain_text, html) bodies."""
    app_name = data.get("app_name", data.get("app_id", "unknown"))
    app_id = data.get("app_id", "")
    count = data.get("finding_count", 0)
    findings = data.get("findings", [])

    # --- plain text ---
    lines = [f"ignis report for {app_name} ({app_id})", f"{count} issue(s) found", ""]
    for f in findings:
        severity = f.get("severity", "").upper()
        emoji = _SEVERITY_EMOJI.get(severity, "•")
        lines += [
            f"{emoji} {severity} · {f.get('rule', '')} · {f.get('stage_name', '')}",
            f.get("message", ""),
            f"Recommendation: {f.get('recommendation', '')}",
            "",
        ]
    plain = "\n".join(lines)

    # --- html ---
    if count == 0:
        findings_html = "<p>No issues found. ✅</p>"
    else:
        rows = []
        for f in findings:
            severity = f.get("severity", "").upper()
            emoji = _SEVERITY_EMOJI.get(severity, "•")
            rows.append(
                f"<tr>"
                f"<td>{emoji} {severity}</td>"
                f"<td><code>{f.get('rule', '')}</code></td>"
                f"<td>{f.get('stage_name', '')}</td>"
                f"<td>{f.get('message', '')}</td>"
                f"<td><em>{f.get('recommendation', '')}</em></td>"
                f"</tr>"
            )
        findings_html = (
            "<table border='1' cellpadding='6' cellspacing='0' style='border-collapse:collapse'>"
            "<tr><th>Severity</th><th>Rule</th><th>Stage</th><th>Message</th><th>Recommendation</th></tr>"
            + "".join(rows)
            + "</table>"
        )

    html = f"""<html><body>
<h2>ignis report — {app_name}</h2>
<p><strong>{count} issue(s) found</strong> · App ID: <code>{app_id}</code></p>
{findings_html}
<hr><p style='color:grey;font-size:0.85em'>Generated by <a href='https://pypi.org/project/spark-ignis/'>spark-ignis</a></p>
</body></html>"""

    return plain, html


def send(
    data: dict,
    *,
    to: str,
    sender: str,
    smtp_host: str,
    smtp_port: int,
    username: str | None,
    password: str | None,
) -> None:
    subject = _build_subject(data)
    plain, html = _build_body(data)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    context = ssl.create_default_context()
    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        if server.has_extn("STARTTLS"):
            server.starttls(context=context)
            server.ehlo()
        if username and password:
            server.login(username, password)
        server.sendmail(sender, to, msg.as_string())
